apiVersion: v1
kind: Service
metadata:
  name: devtinder-frontend
  namespace: devtinder
spec:
  type: NodePort
  selector:
    app: devtinder-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # accessible externally
